require 'W3FPLua.handles.handle'
require 'W3FPLua.handles.location'
require 'W3FPLua.handles.point'
require 'W3FPLua.handles.widget'
require 'W3FPLua.handles.player'
require 'W3FPLua.handles.button'
require 'W3FPLua.handles.dialog'
require 'W3FPLua.handles.destructable'
require 'W3FPLua.handles.camera'
require 'W3FPLua.handles.camera setup'
require 'W3FPLua.handles.blight'
require 'W3FPLua.handles.ability'
require 'W3FPLua.handles.boolean expr'
require 'W3FPLua.handles.unit'
require 'W3FPLua.handles.weather effect'
require 'W3FPLua.handles.terrain deformation'
require 'W3FPLua.handles.special effect'
require 'W3FPLua.handles.spell effect'
require 'W3FPLua.handles.lightning'
require 'W3FPLua.handles.fog of war'