require 'W3FPLua.handles.handle'
require 'W3FPLua.handles.location'
require 'W3FPLua.handles.point'
require 'W3FPLua.handles.widget'
require 'W3FPLua.handles.player'
require 'W3FPLua.handles.button'
require 'W3FPLua.handles.dialog'
require 'W3FPLua.handles.destructable'
require 'W3FPLua.handles.camera'
require 'W3FPLua.handles.camera setup'
require 'W3FPLua.handles.blight'
require 'W3FPLua.handles.ability'
require 'W3FPLua.handles.boolean expr'
require 'W3FPLua.handles.unit'