require 'W3FPLua.API.alliance type'
require 'W3FPLua.API.automation test'
require 'W3FPLua.API.blend mode'
require 'W3FPLua.API.camera field'
require 'W3FPLua.API.camera margin'
require 'W3FPLua.API.campaign'
require 'W3FPLua.API.cheat'
require 'W3FPLua.API.cine filter'
require 'W3FPLua.API.cinematic'
require 'W3FPLua.API.computer AI interface'
require 'W3FPLua.API.doodad'
require 'W3FPLua.API.player color'
require 'W3FPLua.API.player game result'
require 'W3FPLua.API.player state'
require 'W3FPLua.API.race'
require 'W3FPLua.API.tex map flags'